name: upgrade

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 12 * * 1-4'

jobs:
  upgrade:
    name: Upgrade
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'
      - run: npx -p npm-check-updates ncu -p yarn --deep --target minor --upgrade
      - run: yarn set version latest
      - run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn
      - run: yarn build
      - run: yarn format
      - name: Create Patch
        run: |-
          git add .
          git diff --patch --staged > .upgrade.tmp.patch
      - name: Upload patch
        uses: actions/upload-artifact@v2
        with:
          name: .upgrade.tmp.patch
          path: .upgrade.tmp.patch

  pr:
    name: Create Pull Request
    needs: upgrade
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download patch
        uses: actions/download-artifact@v2
        with:
          name: .upgrade.tmp.patch
          path: ${{ runner.temp }}
      - name: Apply patch
        run:
          '[ -s ${{ runner.temp }}/.upgrade.tmp.patch ] && git apply ${{ runner.temp
          }}/.upgrade.tmp.patch || echo "Empty patch. Skipping."'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.YARN_UPGRADE_TOKEN }}
          branch: github-actions/upgrade
          title: 'chore: upgrade dependencies'
          commit-message: 'chore: upgrade dependencies'
